
name: CI

on: ['pull_request']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: VisualSJ/action-javascript-runner@v1
        with:
          script: './workflow.js'

      - uses: VisualSJ/action-javascript-runner@v1
        with:
          script: './workflow.js'

      - name: Check finished
        run: |
          echo 1. Clean up the warehouse
          echo 2. Perform the complete build task
          echo Encountering an error causes an exception to exit the process