name: CI

on: ['pull_request']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: VisualSJ/action-javascript-runner@v0
        with:
          script: './workflow.js'
          data: '{{github.event}}'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
